### ISSUE TITLE
The use of `KEYS`

### ISSUE THREAD

**Issue by itamarhaber** [perrin4869/redis-mdel#1]
Firstly - cool little lib.

Your script is using the evil `KEYS` command. Despite the non-production-safe-warning, you're still risking it and would be better off if you had used `SCAN`. You can do that by calling the new v3.2 `redis.replicate_commands()` from Lua to allow random behavior.

The reasoning is that `KEYS`'s reply could be quite memory intensive and by iterating with `SCAN` you avoid that. This doesn't change the fact that everything will be blocked during the run.

Also, in the near future we'll have Redis Modules and then you'd be able to call [`PDEL` from rxkeys](https://github.com/RedisLabsModules/redex/#pdel-pattern).

**Comment by perrin4869** [comment]
Hi, thanks for suggestion! I need to read up on `SCAN` then. I'm not a redis expert at all, just wanted to factor out this quick little script I was using in my current project :)
So, if `redis.replicate_commands` is available, use `SCAN`, otherwise use the current implementation?

Another question, out of curiosity, why is `PDEL` being added as a module, but not as a core command? Maybe it's better to rename this to `redis-pdel`?

**Comment by perrin4869** [comment]
I'll add a note about `PDEL` in the `README`, might be useful for people to know, since I didn't!

**Comment by perrin4869** [comment]
How does [this](https://github.com/perrin4869/redis-mdel/blob/master/src/mdel.lua) look to you?

**Comment by itamarhaber** [comment]
Looks good  :)

Redis modules in general, and rxkeys in particular, were just announced the other week. The Redis core doesn't have a PDEL-like command since, like KEYS, it is a blocking O(N) scan.

**Comment by perrin4869** [comment]
I see. Do you think it's worth it to rename this package to `redis-pdel` btw? `redis-mdel` might give off the wrong idea, I thought, now that you brought `rxkeys` up.

**Comment by itamarhaber** [comment]
Good question. The M prefix usually denotes a multi-key command, whereas P
is for pattern. That's why I chose PDEL and perhaps you should have too...
that said, I don't think you should change it now - what was was, was was.

**Comment by perrin4869** [comment]
got it! Still I think I'll change it, published this just yesterday, can't do too much damage by moving now. It'll keep bothering me otherwise haha.
Maybe I'll repurpose this one to a command like `MDEL key1, key2, key3, ..., keyn`. Thanks!
